import type { Config } from 'tailwindcss'

const config: Config = {
    darkMode: 'class',
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
                        colors: {
                'on-error': '#690005',
                'secondary-container': '#920703',
                'inverse-primary': '#b22926',
                'secondary-fixed': '#ffdad4',
                'surface-variant': '#353534',
                'tertiary-fixed': '#ffdbd1',
                'surface-dim': '#131313',
                'surface-container-low': '#1c1b1b',
                'outline-variant': '#5a413e',
                'on-secondary-fixed': '#410000',
                'on-primary-container': '#ffb6ae',
                'outline': '#a98986',
                'surface-container-highest': '#353534',
                'on-tertiary': '#601400',
                'surface-container-high': '#2a2a2a',
                'on-secondary-fixed-variant': '#920703',
                'primary-fixed-dim': '#ffb4ac',
                'on-secondary': '#690000',
                'on-secondary-container': '#ff9a8a',
                'background': '#131313',
                'secondary-fixed-dim': '#ffb4a8',
                'primary': '#ffb4ac',
                'on-surface-variant': '#e2beba',
                'on-primary': '#690007',
                'tertiary-fixed-dim': '#ffb5a0',
                'tertiary': '#ffb5a0',
                'error': '#ffb4ab',
                'on-primary-fixed': '#410002',
                'tertiary-container': '#9e2700',
                'on-tertiary-fixed-variant': '#872000',
                'error-container': '#93000a',
                'on-surface': '#e5e2e1',
                'on-background': '#e5e2e1',
                'on-tertiary-fixed': '#3b0900',
                'on-primary-fixed-variant': '#900c12',
                'on-error-container': '#ffdad6',
                'inverse-surface': '#e5e2e1',
                'surface-container': '#201f1f',
                'surface': '#131313',
                'surface-container-lowest': '#0e0e0e',
                'surface-bright': '#393939',
                'on-tertiary-container': '#ffb6a3',
                'primary-container': '#a31d1d',
                'inverse-on-surface': '#313030',
                'secondary': '#ffb4a8',
                'surface-tint': '#ffb4ac',
                'primary-fixed': '#ffdad6',

                brand: {
                    bg: '#090707',
                    surface: '#110D0D',
                    panel: '#1A1212',
                    primary: '#9B1C1C',
                    'primary-light': '#C41E3A',
                    'primary-dark': '#6B0F0F',
                    secondary: '#D4A017',
                    accent: '#C41E3A',
                    text: '#F2EDE8',
                    muted: '#7A6358',
                    dim: '#4A3830',
                },
            },
            fontFamily: {
                display: ['"Playfair Display"', '"Bebas Neue"', 'Georgia', 'serif'],
                body: ['Cairo', 'Inter', 'system-ui', 'sans-serif'],
            },
            keyframes: {
                'fade-up': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
                'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
                'float': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
                'shimmer': { to: { 'background-position': '200% center' } },
                'bounce-soft': { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
                'beanFloat': { '0%,100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-18px) rotate(8deg)' } },
                'drip': { '0%': { transform: 'scaleY(0)', opacity: '0' }, '100%': { transform: 'scaleY(1)', opacity: '1' } },
                'pulse-red': { '0%,100%': { boxShadow: '0 0 0 0 rgba(155,28,28,0.4)' }, '50%': { boxShadow: '0 0 0 12px rgba(155,28,28,0)' } },
            },
            animation: {
                'fade-up': 'fade-up 0.6s ease-out forwards',
                'fade-in': 'fade-in 0.4s ease-out forwards',
                'float': 'float 3s ease-in-out infinite',
                'shimmer': 'shimmer 3s linear infinite',
                'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
                'beanFloat': 'beanFloat 4s ease-in-out infinite',
                'drip': 'drip 0.8s ease-out forwards',
                'pulse-red': 'pulse-red 2s ease-in-out infinite',
            },
        },
    },
    plugins: [],
}

export default config
